<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPUADNIW0008" name="Command line test" tests="1" failures="1" timestamp="2 Dec 2015 12:24:53 GMT" time="13.11" errors="0">
  <testcase name="verifyProductInCard" time="5.093" classname="tests.AddProductToCardTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [0]
	at tests.AddProductToCardTest.verifyProductInCard(AddProductToCardTest.java:15)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- verifyProductInCard -->
</testsuite> <!-- Command line test -->
